language: cpp
compiler:
- gcc
script:
- cmake . && make && make test
# TODO ./tests/integration.sh
sudo: required
before_install:
- wget -O /tmp/snyder.deb 'https://packagecloud.io/mrtazz/snyder/packages/ubuntu/trusty/snyder_0.4.3-1_amd64.deb/download.deb' && sudo dpkg -i /tmp/snyder.deb 
- sudo apt-get install build-essential clang liblog4cxx10-dev libboost-all-dev php-pear php5-dev libcurl4-openssl-dev
- sudo apt-get install libgearman-dev gearman-job-server gearman libgearman7
# TODO install PHP gearman extension
